app_color = "magenta"
collapse_unfocused_tabs = false
show_key_hints = true
# Whether to open priority prompt upon project/task creation. False by default as this might be annoying
always_open_priority_prompt = false

[[column]]
name = "Backlog"
color = "red"
tab = 0

[[column]]
name = "Doing"
color = "yellow"
tab = 0

[[column]]
name = "Review"
color = "green"
tab = 0

[[column]]
name = "Done"
color = "blue"
tab = 1
# Whether to prevent tasks being added deleted or modified in the column (they can still be moved to a different column)
immutable = true
